Add more information about project
SashaErkhov/OurPaint pull request #34
Opened 2024-09-18 18:32 UTC by Ardrass2

2024-09-18 18:34 UTC, TimSkvorchevskij submitted a review, later dismissed

2024-09-18 18:37 UTC, 77maxikov commented on README.md
> +Система автоматизированного проектирование на двумерной плоскости с использованием QT и возможности совместной работы “OurPaint”
Typo

2024-09-18 19:37 UTC, TimSkvorchevskij commented on README.md
> +- **CMake**:  библиотека для модульного тестирования.
исправь

2024-09-18 19:39 UTC, TimSkvorchevskij approved these changes

2024-09-18 20:53 UTC, IBRAGIM-OSKANOV approved these changes

2024-09-18 21:10 UTC, SashaErkhov commented
Если ты добавил про системные требования и возможности, то следует написать про то, как установить и как именно пользоваться твоим продуктом

2024-09-18 21:12 UTC, SashaErkhov requested changes
Допили про установку и возможности

2024-09-19 06:56 UTC, Ardrass2 commented
> Допили про установку и возможности

Не считаю весомой данную информацию

2024-09-19 09:08 UTC, TimSkvorchevskij approved these changes

2024-09-20 22:07 UTC, SashaErkhov approved these changes

2024-09-21 08:12 UTC, nikitanasibullin approved these changes

2024-09-21 08:16 UTC, merged